server:
  port: 8081

spring:
  application:
    name: vetclinic-report

  config:
    import: "optional:file:../.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:5432/vetclinic
    username: admin
    password: ${DB_PASSWORD:?password reports}

  jpa:
    hibernate:
      ddl-auto: validate