version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: vetclinic_db
    environment:
      POSTGRES_DB: vetclinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:?password}
    ports:
      - "5432:5432"
    networks:
      - vet_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d vetclinic" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: vetclinic_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vetclinic
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:?password}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/api/employees/report" ]
      interval: 1s
      timeout: 5s
      start_period: 60s
      retries: 12
    networks:
      - vet_network


  vetclinic-report:
    build: ./vetclinic-report
    container_name: vetclinic_report
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vetclinic
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:?Укажи DB_PASSWORD в .env}
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    networks:
      - vet_network


  vetclinic-gateway:
    build: ./vetclinic-gateway
    container_name: vetclinic_gateway
    ports:
      - "8082:8082"
    environment:
      EMPLOYEE_SERVICE_URL: http://app:8080
      REPORT_SERVICE_URL: http://vetclinic-report:8081
    depends_on:
      app:
        condition: service_started
      vetclinic-report:
        condition: service_started
    networks:
      - vet_network

networks:
  vet_network:
    driver: bridge
